kind: pipeline
type: ssh
name: run-full-sync

trigger:
  branch:
    - master
  event:
    - push

server:
  host:
    from_secret: host
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

steps:
- name: build
  failure : ignore
  commands:
  - sudo apt-get -y install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 curl
  - sudo apt-get -y install libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev
  - sudo apt-get -y install libminiupnpc-dev
  - sudo apt-get -y install libzmq3-dev
  - ./make.sh build
- name: log-config
  failure : ignore
  commands:
  - cat config.log