# Syncs a fresh node to the height avalialable softfork block

kind: pipeline
type: ssh
name: run-full-sync

trigger:
  branch:
    - master
  event:
    - push

server:
  host:
    from_secret: host
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

steps:
- name: build
  commands:
  - ./make.sh build
- name: run
  commands:
  - ./src/defid -daemon
  - sleep 20
  - |
    sh -c '
    block=0
    attempts=0
    tip=$(./src/defi-cli getblockchaininfo | jq  '.softforks | to_entries | map((.value.height)) | max' )
    while [ $block -lt $tip ]; do
        sleep 1
        h=$(./src/defi-cli getblockchaininfo | jq '.blocks' )
        b=$${h:-$block}
        if [ $attempts -gt 60 ]; then
            echo "Node stuck for more than one minute"
            exit 1
        fi
        if [ $block -eq $b ]; then
          attempts=$(($attempts + 1))
        else
          attempts=0
        fi
        block=$${b:-$block}
        echo "===> Block Height $block"
    done    
    '
- name: print_log
  commands:
  - 
- name: shutdown
  commands:
  - ./src/defi-cli stop
  when:
    status:
    - success
    - failure