kind: pipeline
type: ssh
name: run-full-sync

trigger:
  branch:
    - master
  event:
    - push

server:
  host:
    from_secret: host
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

steps:
- name: build
  commands:
  #- sudo apt-get -y install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 curl
  #- sudo apt-get -y install libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev
  #- sudo apt-get -y install libminiupnpc-dev
  #- sudo apt-get -y install libzmq3-dev
  - ./make.sh build
  - ./src/defid -daemon
  - sleep 20
  - |
    sh -c '
    block=0
    attempts=0
    while [ $block -lt 10000 ]; do
        sleep 1
        h=$(./src/defi-cli getblockchaininfo | jq '.blocks' )
        b=$${h:-$block}
        if [ $attempts -gt 60 ]; then
            echo "Node stuck for more than one minute"
            exit 1
        fi
        if [ $block -eq $b ]; then
          attempts=$(($attempts + 1))
        else
          attempts=0
        fi
        block=$${b:-$block}
        echo "===> Block Height $block"
    done    
    '
- name: teardown
  commands:
  - ./src/defi-cli stop
  when:
    status:
    - success
    - failure