kind: pipeline
type: ssh
name: run-full-sync

trigger:
  branch:
    - master
  event:
    - push

server:
  host:
    from_secret: host
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

steps:
- name: build
  commands:
  - ./make.sh build