kind: pipeline
type: ssh
name: run-full-sync

trigger:
  branch:
    - master
  event:
    - push

server:
  host:
    from_secret: host
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

steps:
- name: build
  commands:
  #- sudo apt-get -y install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 curl
  #- sudo apt-get -y install libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev
  #- sudo apt-get -y install libminiupnpc-dev
  #- sudo apt-get -y install libzmq3-dev
  - ./make.sh build
  - ./src/defid -daemon
  - sleep 20
  - ./src/defi-cli getblockchaininfo
  - |
    sh -c '
    block=0
    attempts=0
    while [ $block -lt 10000 ]; do
        sleep 5
        b=$(./src/defi-cli getblockchaininfo | jq '.blocks' )
        block=$${b:-$block}
        echo "===> Block Height $block"
        if [ $attempts -gt 12 ]; then
            echo "Failed to bootstrap after a minute."
            exit 1
        fi
        attempts=$(($attempts + 1))
    done    
    '
  - ./ci/wait_for_blocks.sh
- name: teardown
  commands:
  - ./src/defi-cli stop
  - sudo pkill -f -9 defid
  when:
    status:
    - success
    - failure