---
kind: pipeline
type: ssh
name: echo-something

trigger:
  branch:
  - master
  event:
  - push

server:
  host:
    from_secret: host
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

steps:
- name: greeting
  commands:
  - echo hello world test