name: Full Sync

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs: 
  full-sync:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 4320
    steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build Node
      run: ./make.sh build
    - name: Remove Data Dirs
      run: rm -rf defi
    - name: Create Data Dirs
      run: mkdir -p defi
    - name: Run Node
      run: ./src/defid -datadir="./defi" -server -rpcuser=bob -rpcpassword=bob -daemon
    - name: Sync to Tip
      run: |
        cargo run --manifest-path="./ci/node-monitor/Cargo.toml" --release -- --rpcuser="bob" --rpcpassword="bob"
    - name: Log Debug
      run: cat ./defi/debug.log
  snapshot-sync:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 4320
    steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build Node
      run: ./make.sh build
    - name: Remove Data Dirs
      run: rm -rf defi
    - name: Download Snapshot
      run: curl -s https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/index.txt | tail -n 1 | xargs -I{} wget -O snapshot.zip https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/{}
    - name: Extract Snapshot
      run: unzip snapshot.zip -d defi
    - name: Run Node
      run: ./src/defid -datadir="./defi" -server -rpcuser=bob -rpcpassword=bob -daemon
    - name: Sync to Tip
      run: |
        cargo run --manifest-path="./ci/node-monitor/Cargo.toml" --release -- --rpcuser="bob" --rpcpassword="bob"
    - name: Log Debug
      run: cat ./defi/debug.log