name: Intergration Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs: 
  run-full-sync:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 4320
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: ./make.sh build
    - name: run
      run: ./src/defid -daemon
    - name: monitor-running-node
      run: |
        sleep 20
        cargo run --manifest-path="ci/node-monitor"