name: Intergration Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs: 
  run-full-sync:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 4320
    steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: ./make.sh build
    - name: Remove Dirs
      run: rm -rf defi
    - name: Create Dirs
      run: mkdir -p defi
    - name: run
      run: ./src/defid -datadir="./defi" -server -rpcuser=bob -rpcpassword=bob
    - name: Wait for node
      run: |
        sleep 20
        cargo run --manifest-path="./ci/node-monitor/Cargo.toml" --release -- --rpcuser="bob" --rpcpassword="bob"